accounts/urls.py
from django.urls import path
from accounts.views import user_login, user_logout, signup

urlpatterns = [
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("signup/", signup, name="signup"),
]

coffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def redirect_to_home(request):
    return redirect("list_coffee")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("coffee_beans/", include("coffee_beans.urls")),
    path("", redirect_to_home, name="home"),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("accounts.urls")),
]

coffee_beans/urls.py
from django.urls import path
from coffee_beans.views import (
    list_coffee,
    show_coffee,
    add_coffee,
)

urlpatterns = [
    path("", list_coffee, name="list_coffee"),
    path("<int:id>/", show_coffee, name="show_coffee"),
    path("add_coffee/", add_coffee, name="add_coffee"),
]

reviews/urls.py
from django.urls import path
from reviews.views import (
    add_review,
    user_reviews,
    edit_review
)

urlpatterns = [
    path("<int:id>/add_review/", add_review, name="add_review"),
    path("user_reviews/", user_reviews, name="user_reviews"),
    path("<int:pk>/edit_review/", edit_review, name="edit_review"),

]

coffee_beans/models.py
from django.db import models

class CoffeeBean(models.Model):
    name = models.CharField(max_length=200)
    origin = models.CharField(max_length=200)
    flavor_profile = models.TextField()
    picture = models.URLField(default="URL only")

    def __str__(self):
        return self.name

reviews/models.py
from django.db import models
from django.conf import settings
from coffee_beans.models import CoffeeBean


# Create your models here.
class Review(models.Model):
    rating_choices = [
        (1, '1 Star'),
        (2, '2 Stars'),
        (3, '3 Stars'),
        (4, '4 Stars'),
        (5, '5 Stars'),
    ]

    rating = models.IntegerField(choices=rating_choices)
    review = models.TextField(default='Write your review here')
    review_date = models.DateTimeField(auto_now_add=True)

    reviewer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
    )

    coffee_bean = models.ForeignKey(
        CoffeeBean,
        related_name="reviews",
        on_delete=models.PROTECT,
    )

    class Meta:
        unique_together = ['coffee_bean', 'reviewer']

    def __str__(self):
        return f"{self.coffee_bean.name} - {self.reviewer}"

    def approve(self):
        self.is_approved = True
        self.save()

    def reject(self):
        self.is_approved = False
        self.save()

accounts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )
    password_confirmation = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )

coffee_beans/forms.py
from django.forms import ModelForm
from reviews.models import CoffeeBean


class CoffeeBeanForm(ModelForm):
    class Meta:
        model = CoffeeBean
        fields = [
            "name",
            "origin",
            "flavor_profile",
            "picture"
        ]

reviews/forms.py
from django.forms import ModelForm
from reviews.models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            "rating",
            "review",
        ]

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from accounts.forms import LoginForm, SignUpForm
from django.contrib.auth.models import User


# Create your views here.
def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("list_coffee")
    else:
        form = LoginForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def user_logout(request):
    logout(request)
    return redirect("/")


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password == password_confirmation:
                user = User.objects.create_user(
                    username,
                    password=password,
                )
                login(request, user)

                return redirect("list_coffee")
            else:
                form.add_error(
                    "password", "Password does not match. Try again!"
                )
    else:
        form = SignUpForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)

coffee_beans/views.py
from django.shortcuts import render, get_object_or_404, redirect
from coffee_beans.models import CoffeeBean
from reviews.models import Review
from coffee_beans.forms import CoffeeBeanForm
from django.contrib.auth.decorators import login_required
from django.db.models import Avg


# Create your views here.
def show_coffee(request, id):
    coffee_bean = get_object_or_404(CoffeeBean, id=id)
    reviews = Review.objects.filter(coffee_bean=coffee_bean)
    context = {
        "coffee_bean": coffee_bean,
        "reviews": reviews,
    }
    return render(request, "coffee/detail.html", context)

def list_coffee(request):
    coffee_beans = CoffeeBean.objects.annotate(avg_rating=Avg('reviews__rating'))
    context = {
        "list_coffee": coffee_beans,
    }
    return render(request, "coffee/list.html", context)

@login_required
def add_coffee(request):
    if request.method == "POST":
        form = CoffeeBeanForm(request.POST)
        if form.is_valid():
            new_coffee_bean = form.save(commit=False)
            new_coffee_bean.reviewer = request.user
            new_coffee_bean.save()
            return redirect("list_coffee")
    else:
        form = CoffeeBeanForm()
    context = {
        "CoffeeBeanForm": form,
    }
    return render(request, "coffee/create.html", context)

reviews/views.py
from django.shortcuts import render, get_object_or_404, redirect
from coffee_beans.models import CoffeeBean
from reviews.models import Review
from reviews.forms import ReviewForm
from django.contrib.auth.decorators import login_required


# Create your views here.

def add_review(request, id):
    coffee_bean = get_object_or_404(CoffeeBean, id=id)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(False)
            review.coffee_bean = coffee_bean
            review.reviewer = request.user
            review.save()
            return redirect("show_coffee", id=id)
    else:
        form = ReviewForm()
    context = {
        "ReviewForm": form,
    }

    return render(request, "reviews/create.html", context)

@login_required
def user_reviews(request):
    user_reviews = Review.objects.filter(reviewer=request.user)
    context = {
        "user_reviews": user_reviews,
    }
    return render(request, "reviews/user_reviews.html", context)

def edit_review(request, pk):
    review = get_object_or_404(Review, id=pk)
    if request.method == "POST":
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect("show_coffee", id=pk)
    else:
        form = ReviewForm(instance=review)
    context = {
        "ReviewForm": form,
    }
    return render(request, "reviews/edit.html", context)

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }
        .login-container {
            max-width: 400px;
            margin: 100px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
        }
        input[type="text"],
        input[type="password"] {
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button[type="submit"] {
            padding: 10px;
            background-color: black;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username" required>
            <input type="password" name="password" placeholder="Password" required>
            <button type="submit">Login</button>
        </form>
    </div>
</body>
</html>

accounts/templates/accounts/logout.html
<!-- beanscene/accounts/templates/accounts/logout.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
</head>
<body>
    <h2>Logout</h2>
    <p>You have been successfully logged out.</p>
</body>
</html>

accounts/templates/accounts/signup.html
<!-- beanscene/accounts/templates/accounts/signup.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
</body>
</html>

coffee_beans/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BeanScene</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <a href="{% url 'list_coffee' %}">
            <img src="{% static '/images/2_Fotor.png' %}" alt="Logo" class="logo">
        </a>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'user_reviews' %}">My Reviews</a></li>
                    <li><a href="{% url 'add_coffee' %}">Add a New Bean</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
{% block content %}{% endblock content %}
<footer class="footer">
    <div>coldbrew inc. 2024</div>
</footer>
</body>
</html>

coffee_beans/templates/coffee/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="form-container">
            <h1>Add a New Bean</h1>
            <form method="post" class="coffee-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">{{ CoffeeBeanForm.name.label }}</label>
                    {{ CoffeeBeanForm.name }}
                </div>
                <div class="form-group">
                    <label for="id_origin">{{ CoffeeBeanForm.origin.label }}</label>
                    {{ CoffeeBeanForm.origin }}
                </div>
                <div class="form-group">
                    <label for="id_flavor_profile">{{ CoffeeBeanForm.flavor_profile.label }}</label>
                    {{ CoffeeBeanForm.flavor_profile }}
                </div>
                <div class="form-group">
                    <label for="id_picture">{{ CoffeeBeanForm.picture.label }}</label>
                    {{ CoffeeBeanForm.picture }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </main>
{% endblock content %}

coffee_beans/templates/coffee/detail.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>{{ coffee_bean.name }}</h1>
            <img src="{{ coffee_bean.picture }}" alt="{{ coffee_bean.name }}" style="max-width: 400px; height: auto;">
            <p>Origin: {{ coffee_bean.origin }}</p>
            <p>Flavor Profile: {{ coffee_bean.flavor_profile }}</p>

            <h2>Reviews</h2>
            {% if reviews %}
                <ul>
                    {% for review in reviews %}
                        <li>
                            <p>Rating: {{ review.rating }}</p>
                            <p>Review Date: {{ review.review_date }}</p>
                            <p>Reviewer: {{ review.reviewer.username }}</p>
                            <p>Reviews: {{ review.review }}</p>

                            {% if request.user == review.reviewer %}
                                <a href="{% url 'edit_review' review.id %}">Edit</a>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No reviews available for this coffee bean.</p>
            {% endif %}

            <a href="{% url 'add_review' coffee_bean.id %}">Add a Review</a>
        </div>
    </main>
{% endblock content %}

coffee_beans/templates/coffee/list.html
{% extends 'base.html' %}

{% block content %}
<header>
    <nav>
    </nav>
</header>
<main>
    <h2>Coffee Beans</h2>
    <div class="coffee-grid">
        {% for coffee_beans in list_coffee %}
            <div class="coffee-item">
                <h3>
                    <a href="{% url 'show_coffee' coffee_beans.id %}">{{ coffee_beans.name }}</a>
                </h3>
                <div class="perspective">
                    <div class="card">
                        <a href="{% url 'show_coffee' coffee_beans.id %}">
                            <img src="{{ coffee_beans.picture }}" alt="{{ coffee_beans.name }}">
                        </a>
                    </div>
                </div>
                <p>Average Rating: {{ coffee_beans.avg_rating|default:"No reviews yet" }}</p>
            </div>
        {% endfor %}
    </div>
</main>
{% endblock content %}

{% load static %}

reviews/templates/reviews/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Add a new review</h1>
            <form method ="post">
                {% csrf_token %}
                {{ ReviewForm.as_p }}
                <button>Submit</button>
            </form>
        </div>
    </main>
{% endblock content %}

reviews/templates/reviews/edit.html
{% extends 'base.html' %}

{% block title %}
    Edit {{ review.coffeebean }}
{% endblock title %}

{% block content %}
    <header>
        <nav>
            <p>Home</p>
        </nav>
    </header>
    <main>
        <h1>Edit {{ review.coffeebean }}</h1>
        <form method ="post">
            {% csrf_token %}
            {{ ReviewForm.as_p }}
            <button>Save</button>
        </form>
    </main>
{% endblock content %}

{% load static %}

reviews/templates/reviews/user_reviews.html
{% extends 'base.html' %}

{% block content %}
  <h1>Your Reviews</h1>

  {% if user_reviews %}
    <ul>
      {% for review in user_reviews %}
        <li>
          {{ review.coffee_bean.name }} - {{ review.rating }}
          <a href="{% url 'edit_review' review.id %}">Edit</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>You haven't written any reviews yet.</p>
  {% endif %}
{% endblock content %}